### ISSUE TITLE
Exeption raised in the backend: [Win Error 5]

### ISSUE THREAD

**Issue by LinusHe** [Kapiainen/Lauhdutin#72] opened 2017-05-02 12:27 UTC
Im on the newest Version: Version 2.7.0 Beta 5

I have this Error:
![unbenannt](https://cloud.githubusercontent.com/assets/26716809/25617627/863f2500-2f43-11e7-97be-0be1b0f3bcfc.JPG)

Log:
```
Running on Python 3.6.1
Processing Windows shortcuts...
        Found shortcut 'Battlefield 1.lnk'
Traceback (most recent call last):
  File "D:\Documents\Rainmeter\Skins\Lauhdutin\@Resources\Backend\GetGames.py", line 89, in <module>
    windows_shortcuts_games = windows_shortcuts.get_games()
  File "D:\Documents\Rainmeter\Skins\Lauhdutin\@Resources\Backend\WindowsShortcuts.py", line 29, in get_games
    game_key, game_dict = self.process_shortcut(self.shortcuts_path, shortcut)
  File "D:\Documents\Rainmeter\Skins\Lauhdutin\@Resources\Backend\WindowsShortcuts.py", line 77, in process_shortcut
    output = subprocess.check_output(args)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Linus\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Zugriff verweigert
```

when I delete my own shortcuts, everything works..

**Comment by Kapiainen** [comment] 2017-05-02 12:36
Try setting the value of the skin's *Python path* setting to `python` to show the terminal, try loading the skin again, and post either a screenshot or a text copy of what is printed in the terminal.

**Comment by LinusHe** [comment] 2017-05-02 12:44
after a restart everything worked :)..
sorry ^^

but the skin is loading more than a minute and the console stucks at 

```
Processing Steam games...
                Failed to process 'sharedconfig.vdf'
                Failed to process 'localconfig.vdf'
```
could you help me?

**Comment by LinusHe** [comment] 2017-05-02 12:53
I've uploaded a Video, where you can see it :)
https://drive.google.com/file/d/0BxCdQ_0niCMFQ2RFQVBhUmp0Q00/view?usp=sharing

**Comment by Kapiainen** [comment] 2017-05-02 13:06
The log pertaining to the original issue would indicate that Windows' permission system is interfering with the execution of a VBScript file that is used by the skin to process shortcuts (`.lnk` and `.url` files) in order to get paths to the executables that the shortcuts point to. I haven't touched files relevant to those parts of the skin in a while so perhaps a recent Windows update is causing the problem? By the way do you have Rainmeter installed in a directory that is more heavily regulated by the OS's permission system (e.g. `C:\Program Files\Rainmeter`)?

**Comment by LinusHe** [comment] 2017-05-02 13:10
Okay. The original issue was solved by a simple restart now, as I said. 

Yes, `C:\Program Files\Rainmeter` is my Rainmeter directory. But the skins are stored in `D:\Documents\Rainmeter\Skins\..`

**Comment by LinusHe** [comment] 2017-05-02 13:14
Should I open a new ticket/issue for the other Problem?

**Comment by Kapiainen** [comment] 2017-05-02 13:16
Sure. It may make it easier to find an answer if someone else has the same issue in the future and there is an issue with a title matching their issue.

**Comment by LinusHe** [comment] 2017-05-07 20:18
I have the bug now again. A simple reboot only helps sometimes.

**Comment by Kapiainen** [comment] 2017-05-09 13:20
I tried to look for reports of similar issues elsewhere on the internet, but it looks like in most of those cases the cause was an attempt to remove a file that was being accessed by another process (e.g. antivirus). However, in your case the issue seems to arise when attempting to execute a VBScript file that returns the path that a shortcut (`.lnk` or `.url`) points to. My impression is also that in those other cases it was happening consistently.

Does the error occur at the same point every time (i.e. is a specific shortcut causing the issue or is it seemingly random)?

**Comment by LinusHe** [comment] 2017-05-10 21:34
It's seemingly random.. :/

I figured out, that it must be an error from my external shortcuts. When I removed them and reloaded the skin, the error didnt occur.

**Comment by LinusHe** [comment] 2017-05-25 10:03
When I removed my shortcuts, the 503 error did not occur, but if I now hover over a game, the error occurs that Steam / Blizzard is not running.

**Comment by Kapiainen** [comment] 2017-05-25 15:47
Could you check what the names of the Steam and Blizzard processes are in Windows Task Manager? The skin expects them to be `Steam.exe` and `Battle.net.exe`.

Another thing that you could check is the values of two measures: `SteamMonitor` and `BattlenetMonitor`. Open Rainmeter's log, go to the *Skins* tab, select the skin, and you should see a list of measures and variables on the right-hand side of the window. Starting and closing Steam and/or Blizzard App should change the values of those two measures. Keep in mind that if the skin is set to slide out of view when the mouse is not hovering over the skin (i.e. you are using the skin animations), then you need to make the skin visible by hovering your mouse over the skin in order for those measures to update.

Checking these things will hopefully help to narrow down the source of the issue. I assume there are no errors in Rainmeter's log since you didn't mention any.

**Comment by LinusHe** [comment] 2017-05-26 21:53
No, I do not think that's the problem. The error occurs only when I have the WinError5 and then Reload the skin without the shortcuts. With the shortcuts, the skin does not even start. And without the shortcuts this error occurs.
If the skin starts, so the WinError5 error message does not come, I also do not have this problem.

I believe that this is generally connected with the Windows right system. Somehow me seems so, as if Python simply do not get enough rights for whatever reason.

**Closed** 2018-02-20 14:55 UTC
