### ISSUE TITLE
How do shortcuts work?

### ISSUE THREAD

**Issue by tenzion** [Kapiainen/Lauhdutin#22] opened 2017-02-01 18:16 UTC
I cannot get some of my games shortcuts to work.

Three games that reside on a secondary hdd under the folder "Games" work.

Two games that reside under "Program files (x86)" do not work. The shortcuts I've made are directly to the .exe files and not an internet shortcut pointing to an URL. Just like the three games that work... Also directly to the .exe files.

What could be the issue here? It worked with v2.1.0.

**Comment by Kapiainen** [comment] 2017-02-01 18:59
I'll see if I can reproduce the issue. The Python script that handles Windows shortcuts has not changed since 2.1.0.

**Comment by Kapiainen** [comment] 2017-02-04 10:51
Try using version [2.2.0 Beta 3](https://github.com/Kapiainen/Lauhdutin/releases/tag/2.2.0beta3). The issue is hopefully fixed now.

**Comment by tenzion** [comment] 2017-02-04 13:10
Yup. Works with shortcuts now!
Thanks for the effort once again!!

**Closed** 2017-02-10 20:32 UTC
Labels: bug
